version: '3'
services:
    config:
        image: configserver:latest
        build: ./configserver
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/healthcheck"]
            interval: 10s
            timeout: 2s
            retries: 3
        ports:
            - "8000:8080"
        volumes: 
            - ./configs:/opt/configserver/configs
        networks:
            - microservico-net

    discover:
        image: discover:latest
        build: ./discover
        ports:
            - "7000:8761"
        networks:
            - microservico-net

    broker:
        image: rabbitmq:3-management
        healthcheck:
            test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
            interval: 10s
            timeout: 2s
            retries: 3
        ports:
            - 9000:15672
            - 5671-5672:5671-5672
        networks: 
            - microservico-net
    
    support:
        image: supportservice:latest
        build: ./supportservice
        depends_on: 
            supportDB:
                condition: service_healthy
            broker:
                condition: service_healthy
        ports:
            - "6001:6001"
        environment: 
            - CONFIG_URL=http://config:8080/
            - APP_PROFILE=prod
        networks:
            - microservico-net 
            - microservico-support       

    router:
        image: router:latest
        build: ./router
        ports:
            - "4000:4000"
        environment: 
            - CONFIG_URL=http://config:8080/
            - APP_PROFILE=prod
        networks:
            - microservico-net 

    supportDB:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        healthcheck:
            test: ["CMD-SHELL", "mysqladmin ping --silent"]
            interval: 10s
            timeout: 5s
            retries: 5
        ports: 
            - "3306:3306"
        environment: 
            - MYSQL_ROOT_PASSWORD=fiapteste
        networks:
            - microservico-support
        volumes: 
            - ./supportservice/src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql

    movies:
        image: movies:latest
        build: ./movies
        environment:
            - CONFIG_URL=http://config:8080/
            - APP_PROFILE=prod
        ports:
            - "3000:3000"  
        depends_on:
            - moviesDB
        networks:
            - microservice-movie-network
            - microservico-net

    moviesDB:
        image: postgres
        environment:
            POSTGRES_PASSWORD: "admin"
            POSTGRES_DB: "movies"
            POSTGRES_USER: "admin"
        ports:
            - "15432:5432"  
        volumes:
            - /var/lib/postgresql/data
        networks:
            -  microservice-movie-network

    movieDB-admin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
            PGADMIN_DEFAULT_PASSWORD: "admin"
        ports:
            - "16543:80"
        depends_on:
            - moviesDB
        networks:
            -  microservice-movie-network

networks:
    microservico-net:
    microservico-support:
    microservice-movie-network:
