version: '3'
services:
    discover:
        image: discover:latest
        build: ./discover
        ports:
            - "8761:8761"
        networks:
            - microservico-net

    supportDB:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        ports: 
            - "3306:3306"
        environment: 
            - MYSQL_ROOT_PASSWORD=fiapteste
        networks:
            - microservico-support

networks:
    microservico-net:
    microservico-support:
