version: '3'
services:
    config:
        image: configserver:latest
        build: ./configserver
        ports:
            - "8000:8080"
        volumes: 
            - ./configs:/opt/configserver/configs
        networks:
            - microservico-net

    discover:
        image: discover:latest
        build: ./discover
        ports:
            - "7000:8761"
        networks:
            - microservico-net

    broker:
        image: rabbitmq:3-management
        ports:
            - 9000:15672
            - 5671-5672:5671-5672
        networks: 
            - microservico-net
    
    support:
        image: supportservice:latest
        build: ./supportservice
        depends_on: 
            supportDB:
                condition: service_healthy
        ports:
            - "6001:8080"
        environment: 
            - CONFIG_URL=http://config:8080/
            - APP_PROFILE=prod
        networks:
            - microservico-net 
            - microservico-support       

    supportDB:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        healthcheck:
            test: ["CMD-SHELL", "mysqladmin ping --silent"]
            interval: 10s
            timeout: 5s
            retries: 5
        ports: 
            - "3306:3306"
        environment: 
            - MYSQL_ROOT_PASSWORD=fiapteste
        networks:
            - microservico-support
        volumes: 
            - ./supportservice/src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
    microservico-net:
    microservico-support:
