server:
  port: 4000

logging:
  level:
    com.netflix: DEBUG
    org.springframework.web: DEBUG
    com.thoughtmechanix: DEBUG

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discover:8761/eureka
#  instance:
#    preferIpAddress: true

zuul:
  ignoredServices: "*"
  routes:
    movies-server:
      path: /movies/**
      serviceId: movies
    support-server:
      path: /support/**
      serviceId: supportservice
management:
  endpoints:
    web:
      exposure:
        include: '*'

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 60000